use crate::math::{ConstantFold, Math};
use egg::{rewrite as rw, *};

pub type EGraph = egg::EGraph<Math, ConstantFold>;
pub type Rewrite = egg::Rewrite<Math, ConstantFold>;

fn is_not_zero(var: &str) -> impl Fn(&mut EGraph, Id, &Subst) -> bool {
    let var = var.parse().unwrap();
    move |egraph, _, subst| {
        if let Some(n) = &egraph[subst[var]].data {
            *(n.0) != 0.0
        } else {
            true
        }
    }
}

#[rustfmt::skip]
pub fn rules() -> Vec<(String, Vec<Rewrite>)> { vec![


("math_no_diff_int_KBC_max_rules_100_extended_no_unorderable".to_string(), vec![

rw!("rule_1"; "(+ ?x ?y)" => "(+ ?y ?x)"),
rw!("rule_2"; "(+ ?x 0)" => "?x"),
rw!("rule_3"; "(+ 0 ?x)" => "?x"),
rw!("rule_4"; "(* ?x ?x)" => "(pow ?x 2)"),
rw!("rule_5"; "(* ?x ?y)" => "(* ?y ?x)"),
rw!("rule_6"; "(* ?x 1)" => "?x"),
rw!("rule_7"; "(* ?x 0)" => "0"),
rw!("rule_8"; "(* 1 ?x)" => "?x"),
rw!("rule_9"; "(* 0 ?x)" => "0"),
rw!("rule_10"; "(- ?x ?x)" => "0"),
rw!("rule_11"; "(- ?x 0)" => "?x"),
rw!("rule_12"; "(- 0 1)" => "-1"),
rw!("rule_13"; "(pow ?x 1)" => "?x"),
rw!("rule_14"; "(pow 1 2)" => "1"),
rw!("rule_15"; "(pow 0 2)" => "0"),
rw!("rule_16"; "(+ ?x -1 )" => "(- ?x 1)"),
rw!("rule_17"; "(+ -1 ?x)" => "(- ?x 1)"),
rw!("rule_18"; "(* ?x -1 )" => "(- 0 ?x)"),
rw!("rule_19"; "(* -1 ?x)" => "(- 0 ?x)"),
rw!("rule_20"; "(- ?x -1 )" => "(+ ?x 1)"),
rw!("rule_21"; "(pow -1 2)" => "1"),
rw!("rule_23"; "(+ ?x (- ?y ?z) )" => "(- (+ ?x ?y) ?z)"),
rw!("rule_24"; "(+ ?x (+ ?y ?z) )" => "(+ ?y (+ ?x ?z) )"),
rw!("rule_25"; "(+ (+ ?x ?y) ?z)" => "(+ ?x (+ ?y ?z) )"),
rw!("rule_26"; "(+ (- ?x ?y) ?z)" => "(- (+ ?x ?z) ?y)"),
rw!("rule_30"; "(* ?x (+ 1 ?x) )" => "(+ ?x (pow ?x 2) )"),
rw!("rule_34"; "(* ?x (* ?y ?z) )" => "(* ?y (* ?x ?z) )"),
rw!("rule_35"; "(* ?x (- ?x 1) )" => "(- (pow ?x 2) ?x)"),
rw!("rule_37"; "(* ?x (- 1 ?x) )" => "(- ?x (pow ?x 2) )"),
rw!("rule_39"; "(* ?x (- 0 ?y) )" => "(- 0 (* ?x ?y) )"),
rw!("rule_44"; "(* (* ?x ?y) ?z)" => "(* ?x (* ?y ?z) )"),
rw!("rule_47"; "(* (- 0 ?x) ?y)" => "(- 0 (* ?x ?y) )"),
rw!("rule_48"; "(- ?x (+ ?y ?x) )" => "(- 0 ?y)"),
rw!("rule_50"; "(- ?x (- ?x 1) )" => "1"),
rw!("rule_51"; "(- ?x (- 0 ?x) )" => "(+ ?x ?x)"),
rw!("rule_53"; "(- 0 (+ ?x 1) )" => "(- -1 ?x)"),
rw!("rule_54"; "(- 0 (+ 1 ?x) )" => "(- -1 ?x)"),
rw!("rule_55"; "(- 0 (- ?x 1) )" => "(- 1 ?x)"),
rw!("rule_56"; "(- 0 (- 0 ?x) )" => "?x"),
rw!("rule_57"; "(- (+ ?x ?y) ?y)" => "?x"),
rw!("rule_58"; "(- (+ ?x 1) ?y)" => "(- ?x (- ?y 1) )"),
rw!("rule_59"; "(- (+ 1 ?x) ?y)" => "(- ?x (- ?y 1) )"),
rw!("rule_60"; "(- (- ?x ?y) ?z)" => "(- ?x (+ ?y ?z) )"),
rw!("rule_62"; "(- ?x (- -1 1) )" => "(+ ?x (+ 1 1) )"),
rw!("rule_63"; "(- -1 (- ?x 1) )" => "(- 0 ?x)"),
rw!("rule_64"; "(+ (* ?x ?y) (* ?x ?z) )" => "(* ?x (+ ?y ?z) )"),
rw!("rule_65"; "(+ (* ?x ?y) (* ?y ?z) )" => "(* ?y (+ ?x ?z) )"),
rw!("rule_66"; "(+ (* ?x ?y) (* ?z ?y) )" => "(* ?y (+ ?x ?z) )"),
rw!("rule_67"; "(+ (pow ?x 2) (* ?x ?y) )" => "(* ?x (+ ?x ?y) )"),
rw!("rule_68"; "(* ?x (* ?x (pow ?y 2) ) )" => "(pow (* ?x ?y) 2)"),
rw!("rule_69"; "(- 0 (- (* ?x ?y) ?x) )" => "(- ?x (* ?x ?y) )"),
rw!("rule_70"; "(- (+ ?x ?y) (+ ?x ?z) )" => "(- ?y ?z)"),
rw!("rule_71"; "(- (+ ?x (+ ?y ?z) ) ?y)" => "(+ ?x ?z)"),
rw!("rule_72"; "(- (* ?x (+ 1 1) ) ?x)" => "?x"),
rw!("rule_73"; "(pow ?x 0)" => "1" if is_not_zero("?x")),
rw!("rule_74"; "(/ ?x ?x)" => "1" if is_not_zero("?x")),
rw!("rule_75"; "(* ?x (/ 1 ?x) )" => "1" if is_not_zero("?x")),
rw!("rule_76"; "(pow ?x -1 )" => "(/ 1 ?x)" if is_not_zero("?x")),
rw!("rule_77"; "(* ?y (pow ?x -1 ) )" => "(/ ?y ?x)" if is_not_zero("?x")),
rw!("rule_78"; "(* (pow ?x ?y) (pow ?x ?z) )" => "(pow ?x (+ ?y ?z) )" if is_not_zero("?x")),
rw!("assoc_add"; "(+ ?x (+ ?y ?z) )" => "(+ (+ ?x ?y) ?z)"),
rw!("assoc_mul"; "(* ?x (* ?y ?z) )" => "(* (* ?x ?y) ?z)"),
rw!("sub_canon"; "(- ?x ?y)" => "(+ ?x (* -1 ?y) )"),
rw!("div_canon"; "(/ ?x ?y)" => "(* ?x (pow ?y -1 ) )" if is_not_zero("?y")),
rw!("add_zero"; "?x" => "(+ ?x 0)"),
rw!("mul_one"; "?x" => "(* ?x 1)"),
rw!("distribute"; "(* ?x (+ ?y ?z) )" => "(+ (* ?x ?y) (* ?x ?z) )"),
rw!("pow2"; "(pow ?x 2)" => "(* ?x ?x)"),
]),

("math_no_diff_int_KBC_max_rules_150_extended_no_unorderable".to_string(), vec![

rw!("rule_1"; "(+ ?x ?y)" => "(+ ?y ?x)"),
rw!("rule_2"; "(+ ?x 0)" => "?x"),
rw!("rule_3"; "(+ 0 ?x)" => "?x"),
rw!("rule_4"; "(* ?x ?x)" => "(pow ?x 2)"),
rw!("rule_5"; "(* ?x ?y)" => "(* ?y ?x)"),
rw!("rule_6"; "(* ?x 1)" => "?x"),
rw!("rule_7"; "(* ?x 0)" => "0"),
rw!("rule_8"; "(* 1 ?x)" => "?x"),
rw!("rule_9"; "(* 0 ?x)" => "0"),
rw!("rule_10"; "(- ?x ?x)" => "0"),
rw!("rule_11"; "(- ?x 0)" => "?x"),
rw!("rule_12"; "(- 0 1)" => "-1"),
rw!("rule_13"; "(pow ?x 1)" => "?x"),
rw!("rule_14"; "(pow 1 2)" => "1"),
rw!("rule_15"; "(pow 0 2)" => "0"),
rw!("rule_16"; "(+ ?x -1 )" => "(- ?x 1)"),
rw!("rule_17"; "(+ -1 ?x)" => "(- ?x 1)"),
rw!("rule_18"; "(* ?x -1 )" => "(- 0 ?x)"),
rw!("rule_19"; "(* -1 ?x)" => "(- 0 ?x)"),
rw!("rule_20"; "(- ?x -1 )" => "(+ ?x 1)"),
rw!("rule_21"; "(pow -1 2)" => "1"),
rw!("rule_24"; "(+ ?x (- ?y ?z) )" => "(- ?x (- ?z ?y) )"),
rw!("rule_26"; "(+ ?x (+ ?y ?z) )" => "(+ ?y (+ ?x ?z) )"),
rw!("rule_27"; "(+ (+ ?x ?y) ?z)" => "(+ ?x (+ ?y ?z) )"),
rw!("rule_28"; "(+ (- ?x ?y) ?z)" => "(- ?x (- ?y ?z) )"),
rw!("rule_32"; "(* ?x (+ 1 ?x) )" => "(+ ?x (pow ?x 2) )"),
rw!("rule_36"; "(* ?x (* ?y ?z) )" => "(* ?y (* ?x ?z) )"),
rw!("rule_37"; "(* ?x (- ?x 1) )" => "(- (pow ?x 2) ?x)"),
rw!("rule_39"; "(* ?x (- 1 ?x) )" => "(- ?x (pow ?x 2) )"),
rw!("rule_41"; "(* ?x (- 0 ?y) )" => "(- 0 (* ?x ?y) )"),
rw!("rule_46"; "(* (* ?x ?y) ?z)" => "(* ?x (* ?y ?z) )"),
rw!("rule_49"; "(* (- 0 ?x) ?y)" => "(- 0 (* ?x ?y) )"),
rw!("rule_50"; "(- ?x (+ ?y ?x) )" => "(- 0 ?y)"),
rw!("rule_53"; "(- ?x (- 0 ?y) )" => "(+ ?x ?y)"),
rw!("rule_54"; "(- ?x (- ?y ?z) )" => "(- ?z (- ?y ?x) )"),
rw!("rule_57"; "(- 0 (+ ?x 1) )" => "(- -1 ?x)"),
rw!("rule_58"; "(- 0 (+ 1 ?x) )" => "(- -1 ?x)"),
rw!("rule_59"; "(- (+ ?x ?y) ?z)" => "(- ?x (- ?z ?y) )"),
rw!("rule_60"; "(- (- ?x ?y) ?z)" => "(- ?x (+ ?y ?z) )"),
rw!("rule_62"; "(pow (- 0 ?x) 2)" => "(pow ?x 2)"),
rw!("rule_64"; "(- ?x (- -1 1) )" => "(+ ?x (+ 1 1) )"),
rw!("rule_65"; "(pow (- -1 ?x) 2)" => "(pow (+ ?x 1) 2)"),
rw!("rule_69"; "(+ ?x (* ?x (- ?y 1) ) )" => "(* ?x ?y)"),
rw!("rule_70"; "(+ ?x (* (- ?y 1) ?x) )" => "(* ?x ?y)"),
rw!("rule_71"; "(+ (* ?x ?y) (* ?x ?z) )" => "(* ?x (+ ?y ?z) )"),
rw!("rule_72"; "(+ (* ?x ?y) (* ?y ?z) )" => "(* ?y (+ ?x ?z) )"),
rw!("rule_73"; "(+ (* ?x ?y) (* ?z ?y) )" => "(* ?y (+ ?x ?z) )"),
rw!("rule_74"; "(+ (pow ?x 2) (* ?y ?x) )" => "(* ?x (+ ?x ?y) )"),
rw!("rule_77"; "(* ?x (+ 1 (* ?x ?y) ) )" => "(+ ?x (* (pow ?x 2) ?y) )"),
rw!("rule_79"; "(* ?x (* ?x (+ 1 1) ) )" => "(+ (pow ?x 2) (pow ?x 2) )"),
rw!("rule_80"; "(* ?x (* ?x (pow ?x 2) ) )" => "(pow (pow ?x 2) 2)"),
rw!("rule_81"; "(* ?x (* ?x (pow ?y 2) ) )" => "(pow (* ?x ?y) 2)"),
rw!("rule_85"; "(* ?x (* (pow ?y 2) ?x) )" => "(pow (* ?x ?y) 2)"),
rw!("rule_89"; "(* (pow ?x 2) (pow ?y 2) )" => "(pow (* ?x ?y) 2)"),
rw!("rule_90"; "(* (+ ?x (* ?x ?y) ) ?z)" => "(* ?x (* (+ ?y 1) ?z) )"),
rw!("rule_92"; "(- ?x (* (+ 1 1) ?x) )" => "(- 0 ?x)"),
rw!("rule_93"; "(- ?x (* (- 1 ?y) ?x) )" => "(* ?x ?y)"),
rw!("rule_94"; "(- (* ?x (+ ?y 1) ) ?x)" => "(* ?x ?y)"),
rw!("rule_95"; "(- (* ?x (+ 1 ?y) ) ?x)" => "(* ?x ?y)"),
rw!("rule_96"; "(- (* (+ ?x 1) ?y) ?y)" => "(* ?x ?y)"),
rw!("rule_97"; "(- (* (+ 1 ?x) ?y) ?y)" => "(* ?x ?y)"),
rw!("rule_99"; "(pow ?x 0)" => "1" if is_not_zero("?x")),
rw!("rule_100"; "(/ ?x ?x)" => "1" if is_not_zero("?x")),
rw!("rule_101"; "(* ?x (/ 1 ?x) )" => "1" if is_not_zero("?x")),
rw!("rule_102"; "(pow ?x -1 )" => "(/ 1 ?x)" if is_not_zero("?x")),
rw!("rule_103"; "(* ?y (pow ?x -1 ) )" => "(/ ?y ?x)" if is_not_zero("?x")),
rw!("rule_104"; "(* (pow ?x ?y) (pow ?x ?z) )" => "(pow ?x (+ ?y ?z) )" if is_not_zero("?x")),
rw!("assoc_add"; "(+ ?x (+ ?y ?z) )" => "(+ (+ ?x ?y) ?z)"),
rw!("assoc_mul"; "(* ?x (* ?y ?z) )" => "(* (* ?x ?y) ?z)"),
rw!("sub_canon"; "(- ?x ?y)" => "(+ ?x (* -1 ?y) )"),
rw!("div_canon"; "(/ ?x ?y)" => "(* ?x (pow ?y -1 ) )" if is_not_zero("?y")),
rw!("add_zero"; "?x" => "(+ ?x 0)"),
rw!("mul_one"; "?x" => "(* ?x 1)"),
rw!("distribute"; "(* ?x (+ ?y ?z) )" => "(+ (* ?x ?y) (* ?x ?z) )"),
rw!("pow2"; "(pow ?x 2)" => "(* ?x ?x)"),
]),

("math_no_diff_int_KBC_max_rules_200_extended_no_unorderable".to_string(), vec![

rw!("rule_1"; "(+ ?x ?y)" => "(+ ?y ?x)"),
rw!("rule_2"; "(+ ?x 0)" => "?x"),
rw!("rule_3"; "(+ 0 ?x)" => "?x"),
rw!("rule_4"; "(* ?x ?x)" => "(pow ?x 2)"),
rw!("rule_5"; "(* ?x ?y)" => "(* ?y ?x)"),
rw!("rule_6"; "(* ?x 1)" => "?x"),
rw!("rule_7"; "(* ?x 0)" => "0"),
rw!("rule_8"; "(* 1 ?x)" => "?x"),
rw!("rule_9"; "(* 0 ?x)" => "0"),
rw!("rule_10"; "(- ?x ?x)" => "0"),
rw!("rule_11"; "(- ?x 0)" => "?x"),
rw!("rule_12"; "(- 0 1)" => "-1"),
rw!("rule_13"; "(pow ?x 1)" => "?x"),
rw!("rule_14"; "(pow 1 2)" => "1"),
rw!("rule_15"; "(pow 0 2)" => "0"),
rw!("rule_16"; "(+ ?x -1 )" => "(- ?x 1)"),
rw!("rule_17"; "(+ -1 ?x)" => "(- ?x 1)"),
rw!("rule_18"; "(* ?x -1 )" => "(- 0 ?x)"),
rw!("rule_19"; "(* -1 ?x)" => "(- 0 ?x)"),
rw!("rule_20"; "(- ?x -1 )" => "(+ ?x 1)"),
rw!("rule_21"; "(pow -1 2)" => "1"),
rw!("rule_24"; "(+ ?x (- ?y ?z) )" => "(- ?x (- ?z ?y) )"),
rw!("rule_26"; "(+ ?x (+ ?x ?y) )" => "(+ ?y (+ ?x ?x) )"),
rw!("rule_27"; "(+ ?x (+ ?y ?z) )" => "(+ ?y (+ ?x ?z) )"),
rw!("rule_28"; "(+ (+ ?x ?y) ?z)" => "(+ ?x (+ ?y ?z) )"),
rw!("rule_29"; "(+ (- ?x ?y) ?z)" => "(- ?x (- ?y ?z) )"),
rw!("rule_33"; "(* ?x (+ 1 ?x) )" => "(+ ?x (pow ?x 2) )"),
rw!("rule_37"; "(* ?x (* ?y ?z) )" => "(* ?y (* ?x ?z) )"),
rw!("rule_38"; "(* ?x (- ?x 1) )" => "(- (pow ?x 2) ?x)"),
rw!("rule_40"; "(* ?x (- 1 ?x) )" => "(- ?x (pow ?x 2) )"),
rw!("rule_42"; "(* ?x (- 0 ?y) )" => "(- 0 (* ?x ?y) )"),
rw!("rule_47"; "(* (* ?x ?y) ?z)" => "(* ?x (* ?y ?z) )"),
rw!("rule_50"; "(* (- 0 ?x) ?y)" => "(- 0 (* ?x ?y) )"),
rw!("rule_51"; "(- ?x (+ ?y ?x) )" => "(- 0 ?y)"),
rw!("rule_53"; "(- ?x (- 0 ?y) )" => "(+ ?x ?y)"),
rw!("rule_54"; "(- ?x (- ?y ?z) )" => "(- ?z (- ?y ?x) )"),
rw!("rule_57"; "(- 0 (+ ?x 1) )" => "(- -1 ?x)"),
rw!("rule_58"; "(- 0 (+ 1 ?x) )" => "(- -1 ?x)"),
rw!("rule_59"; "(- (+ ?x ?y) ?z)" => "(- ?x (- ?z ?y) )"),
rw!("rule_60"; "(- (- ?x ?y) ?z)" => "(- ?x (+ ?y ?z) )"),
rw!("rule_61"; "(pow (- ?x ?y) 2)" => "(pow (- ?y ?x) 2)"),
rw!("rule_63"; "(- ?x (- -1 ?y) )" => "(+ ?x (+ ?y 1) )"),
rw!("rule_71"; "(+ ?x (* ?x (- ?y 1) ) )" => "(* ?x ?y)"),
rw!("rule_76"; "(+ ?x (* (- ?y 1) ?x) )" => "(* ?x ?y)"),
rw!("rule_80"; "(+ (* ?x ?y) (* ?x ?z) )" => "(* ?x (+ ?y ?z) )"),
rw!("rule_81"; "(+ (* ?x ?y) (* ?y ?z) )" => "(* ?y (+ ?x ?z) )"),
rw!("rule_82"; "(+ (* ?x ?y) (* ?z ?y) )" => "(* ?y (+ ?x ?z) )"),
rw!("rule_83"; "(+ (pow ?x 2) (* ?y ?x) )" => "(* ?x (+ ?x ?y) )"),
rw!("rule_91"; "(* ?x (+ 1 (* ?x ?y) ) )" => "(+ ?x (* (pow ?x 2) ?y) )"),
rw!("rule_93"; "(* ?x (* ?x (+ 1 1) ) )" => "(+ (pow ?x 2) (pow ?x 2) )"),
rw!("rule_95"; "(* ?x (* ?x (pow ?x 2) ) )" => "(pow (pow ?x 2) 2)"),
rw!("rule_96"; "(* ?x (* ?x (pow ?y 2) ) )" => "(pow (* ?x ?y) 2)"),
rw!("rule_104"; "(* ?x (* (pow ?y 2) ?x) )" => "(pow (* ?x ?y) 2)"),
rw!("rule_116"; "(* (pow ?x 2) (pow ?y 2) )" => "(pow (* ?x ?y) 2)"),
rw!("rule_118"; "(* (+ ?x (* ?x ?y) ) ?z)" => "(* ?x (* (+ ?y 1) ?z) )"),
rw!("rule_119"; "(* (+ ?x (* ?y ?x) ) ?z)" => "(* ?x (* (+ ?y 1) ?z) )"),
rw!("rule_122"; "(- ?x (* (+ 1 1) ?x) )" => "(- 0 ?x)"),
rw!("rule_123"; "(- ?x (* (- 1 ?y) ?x) )" => "(* ?x ?y)"),
rw!("rule_124"; "(- ?x (- ?y (+ ?z ?w) ) )" => "(- ?z (- ?y (+ ?x ?w) ) )"),
rw!("rule_125"; "(- 0 (+ ?x (+ ?y 1) ) )" => "(- -1 (+ ?x ?y) )"),
rw!("rule_126"; "(- 0 (* ?x (+ ?y 1) ) )" => "(* ?x (- -1 ?y) )"),
rw!("rule_127"; "(- 0 (* ?x (- ?y ?z) ) )" => "(* ?x (- ?z ?y) )"),
rw!("rule_128"; "(- 0 (* (+ ?x 1) ?y) )" => "(* ?y (- -1 ?x) )"),
rw!("rule_129"; "(- (* ?x ?y) (* ?x ?z) )" => "(* ?x (- ?y ?z) )"),
rw!("rule_131"; "(- (* ?x (+ 1 ?y) ) ?x)" => "(* ?x ?y)"),
rw!("rule_132"; "(- (* (+ ?x 1) ?y) ?y)" => "(* ?x ?y)"),
rw!("rule_133"; "(- (* (+ 1 ?x) ?y) ?y)" => "(* ?x ?y)"),
rw!("rule_135"; "(pow ?x 0)" => "1" if is_not_zero("?x")),
rw!("rule_136"; "(/ ?x ?x)" => "1" if is_not_zero("?x")),
rw!("rule_137"; "(* ?x (/ 1 ?x) )" => "1" if is_not_zero("?x")),
rw!("rule_138"; "(pow ?x -1 )" => "(/ 1 ?x)" if is_not_zero("?x")),
rw!("rule_139"; "(* ?y (pow ?x -1 ) )" => "(/ ?y ?x)" if is_not_zero("?x")),
rw!("rule_140"; "(* (pow ?x ?y) (pow ?x ?z) )" => "(pow ?x (+ ?y ?z) )" if is_not_zero("?x")),
rw!("assoc_add"; "(+ ?x (+ ?y ?z) )" => "(+ (+ ?x ?y) ?z)"),
rw!("assoc_mul"; "(* ?x (* ?y ?z) )" => "(* (* ?x ?y) ?z)"),
rw!("sub_canon"; "(- ?x ?y)" => "(+ ?x (* -1 ?y) )"),
rw!("div_canon"; "(/ ?x ?y)" => "(* ?x (pow ?y -1 ) )" if is_not_zero("?y")),
rw!("add_zero"; "?x" => "(+ ?x 0)"),
rw!("mul_one"; "?x" => "(* ?x 1)"),
rw!("distribute"; "(* ?x (+ ?y ?z) )" => "(+ (* ?x ?y) (* ?x ?z) )"),
rw!("pow2"; "(pow ?x 2)" => "(* ?x ?x)"),
]),

("math_no_diff_int_KBC_max_rules_40_extended_no_unorderable".to_string(), vec![
rw!("rule_0"; "(+ ?x ?y)" => "(+ ?y ?x)"),
rw!("rule_1"; "(+ ?x 0)" => "?x"),
rw!("rule_2"; "(+ 0 ?x)" => "?x"),
rw!("rule_3"; "(* ?x ?x)" => "(pow ?x 2)"),
rw!("rule_4"; "(* ?x ?y)" => "(* ?y ?x)"),
rw!("rule_5"; "(* ?x 1)" => "?x"),
rw!("rule_6"; "(* ?x 0)" => "0"),
rw!("rule_7"; "(* 1 ?x)" => "?x"),
rw!("rule_8"; "(* 0 ?x)" => "0"),
rw!("rule_9"; "(- ?x ?x)" => "0"),
rw!("rule_10"; "(- ?x 0)" => "?x"),
rw!("rule_11"; "(- 0 1)" => "-1"),
rw!("rule_12"; "(pow ?x 1)" => "?x"),
rw!("rule_13"; "(pow 1 2)" => "1"),
rw!("rule_14"; "(pow 0 2)" => "0"),
rw!("rule_15"; "(+ ?x -1 )" => "(- ?x 1)"),
rw!("rule_16"; "(+ -1 ?x)" => "(- ?x 1)"),
rw!("rule_17"; "(* ?x -1 )" => "(- 0 ?x)"),
rw!("rule_18"; "(* -1 ?x)" => "(- 0 ?x)"),
rw!("rule_19"; "(pow -1 2)" => "(- 0 -1 )"),
rw!("rule_20"; "(+ ?x (- ?y ?z) )" => "(- (+ ?x ?y) ?z)"),
rw!("rule_21"; "(+ ?x (+ ?y ?z) )" => "(+ ?y (+ ?x ?z) )"),
rw!("rule_22"; "(+ (+ ?x ?y) ?z)" => "(+ ?x (+ ?y ?z) )"),
rw!("rule_23"; "(+ (- ?x ?y) ?z)" => "(- (+ ?x ?z) ?y)"),

rw!("rule_27"; "(* ?x (* ?y ?z) )" => "(* ?y (* ?x ?z) )"),
rw!("rule_28"; "(* (* ?x ?y) ?z)" => "(* ?x (* ?y ?z) )"),
rw!("rule_29"; "(- (+ ?x ?y) ?y)" => "?x"),
rw!("rule_30"; "(+ (* ?x ?y) (* ?x ?z) )" => "(* ?x (+ ?y ?z) )"),
rw!("rule_31"; "(pow ?x 0)" => "1" if is_not_zero("?x")),
rw!("rule_32"; "(/ ?x ?x)" => "1" if is_not_zero("?x")),
rw!("rule_33"; "(* ?x (/ 1 ?x) )" => "1" if is_not_zero("?x")),
rw!("rule_34"; "(pow ?x -1 )" => "(/ 1 ?x)" if is_not_zero("?x")),
rw!("rule_35"; "(* ?y (pow ?x -1 ) )" => "(/ ?y ?x)" if is_not_zero("?x")),
rw!("rule_36"; "(* (pow ?x ?y) (pow ?x ?z) )" => "(pow ?x (+ ?y ?z) )" if is_not_zero("?x")),
rw!("assoc_add"; "(+ ?x (+ ?y ?z) )" => "(+ (+ ?x ?y) ?z)"),
rw!("assoc_mul"; "(* ?x (* ?y ?z) )" => "(* (* ?x ?y) ?z)"),
rw!("sub_canon"; "(- ?x ?y)" => "(+ ?x (* -1 ?y) )"),
rw!("div_canon"; "(/ ?x ?y)" => "(* ?x (pow ?y -1 ) )" if is_not_zero("?y")),
rw!("add_zero"; "?x" => "(+ ?x 0)"),
rw!("mul_one"; "?x" => "(* ?x 1)"),
rw!("distribute"; "(* ?x (+ ?y ?z) )" => "(+ (* ?x ?y) (* ?x ?z) )"),
rw!("pow2"; "(pow ?x 2)" => "(* ?x ?x)"),
]),

("math_no_diff_int_KBC_max_rules_60_extended_no_unorderable".to_string(), vec![

rw!("rule_1"; "(+ ?x ?y)" => "(+ ?y ?x)"),
rw!("rule_2"; "(+ ?x 0)" => "?x"),
rw!("rule_3"; "(+ 0 ?x)" => "?x"),
rw!("rule_4"; "(* ?x ?x)" => "(pow ?x 2)"),
rw!("rule_5"; "(* ?x ?y)" => "(* ?y ?x)"),
rw!("rule_6"; "(* ?x 1)" => "?x"),
rw!("rule_7"; "(* ?x 0)" => "0"),
rw!("rule_8"; "(* 1 ?x)" => "?x"),
rw!("rule_9"; "(* 0 ?x)" => "0"),
rw!("rule_10"; "(- ?x ?x)" => "0"),
rw!("rule_11"; "(- ?x 0)" => "?x"),
rw!("rule_12"; "(- 0 1)" => "-1"),
rw!("rule_13"; "(pow ?x 1)" => "?x"),
rw!("rule_14"; "(pow 1 2)" => "1"),
rw!("rule_15"; "(pow 0 2)" => "0"),
rw!("rule_16"; "(+ ?x -1 )" => "(- ?x 1)"),
rw!("rule_17"; "(+ -1 ?x)" => "(- ?x 1)"),
rw!("rule_18"; "(* ?x -1 )" => "(- 0 ?x)"),
rw!("rule_19"; "(* -1 ?x)" => "(- 0 ?x)"),
rw!("rule_20"; "(pow -1 2)" => "(- 0 -1 )"),
rw!("rule_22"; "(+ ?x (- ?y ?z) )" => "(- (+ ?x ?y) ?z)"),
rw!("rule_24"; "(+ ?x (+ ?y ?z) )" => "(+ ?y (+ ?x ?z) )"),
rw!("rule_25"; "(+ (+ ?x ?y) ?z)" => "(+ ?x (+ ?y ?z) )"),
rw!("rule_26"; "(+ (- ?x ?y) ?z)" => "(- (+ ?x ?z) ?y)"),
rw!("rule_27"; "(* ?x (+ ?x 1) )" => "(+ ?x (pow ?x 2) )"),
rw!("rule_32"; "(* ?x (* ?y ?z) )" => "(* ?y (* ?x ?z) )"),
rw!("rule_36"; "(* (* ?x ?y) ?z)" => "(* ?x (* ?y ?z) )"),
rw!("rule_37"; "(- ?x (+ ?x ?y) )" => "(- 0 ?y)"),
rw!("rule_38"; "(- ?x (+ 1 ?x) )" => "-1"),
rw!("rule_39"; "(- 0 (+ ?x 1) )" => "(- -1 ?x)"),
rw!("rule_40"; "(- 0 (+ 1 ?x) )" => "(- -1 ?x)"),
rw!("rule_41"; "(- (+ ?x ?y) ?y)" => "?x"),
rw!("rule_42"; "(- (- ?x ?y) ?x)" => "(- 0 ?y)"),
rw!("rule_43"; "(- (- ?x ?y) 1)" => "(- ?x (+ ?y 1) )"),
rw!("rule_44"; "(- (- ?x ?y) ?z)" => "(- (- ?x ?z) ?y)"),
rw!("rule_46"; "(+ (* ?x ?y) (* ?x ?z) )" => "(* ?x (+ ?y ?z) )"),
rw!("rule_47"; "(pow ?x 0)" => "1" if is_not_zero("?x")),
rw!("rule_48"; "(/ ?x ?x)" => "1" if is_not_zero("?x")),
rw!("rule_49"; "(* ?x (/ 1 ?x) )" => "1" if is_not_zero("?x")),
rw!("rule_50"; "(pow ?x -1 )" => "(/ 1 ?x)" if is_not_zero("?x")),
rw!("rule_51"; "(* ?y (pow ?x -1 ) )" => "(/ ?y ?x)" if is_not_zero("?x")),
rw!("rule_52"; "(* (pow ?x ?y) (pow ?x ?z) )" => "(pow ?x (+ ?y ?z) )" if is_not_zero("?x")),
rw!("assoc_add"; "(+ ?x (+ ?y ?z) )" => "(+ (+ ?x ?y) ?z)"),
rw!("assoc_mul"; "(* ?x (* ?y ?z) )" => "(* (* ?x ?y) ?z)"),
rw!("sub_canon"; "(- ?x ?y)" => "(+ ?x (* -1 ?y) )"),
rw!("div_canon"; "(/ ?x ?y)" => "(* ?x (pow ?y -1 ) )" if is_not_zero("?y")),
rw!("add_zero"; "?x" => "(+ ?x 0)"),
rw!("mul_one"; "?x" => "(* ?x 1)"),
rw!("distribute"; "(* ?x (+ ?y ?z) )" => "(+ (* ?x ?y) (* ?x ?z) )"),
rw!("pow2"; "(pow ?x 2)" => "(* ?x ?x)"),
]),

("math_no_diff_int_KBC_max_rules_80_extended_no_unorderable".to_string(), vec![

rw!("rule_1"; "(+ ?x ?y)" => "(+ ?y ?x)"),
rw!("rule_2"; "(+ ?x 0)" => "?x"),
rw!("rule_3"; "(+ 0 ?x)" => "?x"),
rw!("rule_4"; "(* ?x ?x)" => "(pow ?x 2)"),
rw!("rule_5"; "(* ?x ?y)" => "(* ?y ?x)"),
rw!("rule_6"; "(* ?x 1)" => "?x"),
rw!("rule_7"; "(* ?x 0)" => "0"),
rw!("rule_8"; "(* 1 ?x)" => "?x"),
rw!("rule_9"; "(* 0 ?x)" => "0"),
rw!("rule_10"; "(- ?x ?x)" => "0"),
rw!("rule_11"; "(- ?x 0)" => "?x"),
rw!("rule_12"; "(- 0 1)" => "-1"),
rw!("rule_13"; "(pow ?x 1)" => "?x"),
rw!("rule_14"; "(pow 1 2)" => "1"),
rw!("rule_15"; "(pow 0 2)" => "0"),
rw!("rule_16"; "(+ ?x -1 )" => "(- ?x 1)"),
rw!("rule_17"; "(+ -1 ?x)" => "(- ?x 1)"),
rw!("rule_18"; "(* ?x -1 )" => "(- 0 ?x)"),
rw!("rule_19"; "(* -1 ?x)" => "(- 0 ?x)"),
rw!("rule_20"; "(- ?x -1 )" => "(+ ?x 1)"),
rw!("rule_21"; "(pow -1 2)" => "1"),
rw!("rule_23"; "(+ ?x (- ?y ?z) )" => "(- (+ ?x ?y) ?z)"),
rw!("rule_24"; "(+ ?x (+ ?y ?z) )" => "(+ ?y (+ ?x ?z) )"),
rw!("rule_25"; "(+ (+ ?x ?y) ?z)" => "(+ ?x (+ ?y ?z) )"),
rw!("rule_26"; "(+ (- ?x ?y) ?z)" => "(- (+ ?x ?z) ?y)"),
rw!("rule_29"; "(* ?x (+ 1 ?x) )" => "(+ ?x (pow ?x 2) )"),
rw!("rule_33"; "(* ?x (* ?y ?z) )" => "(* ?y (* ?x ?z) )"),
rw!("rule_35"; "(* ?x (- 0 ?y) )" => "(- 0 (* ?x ?y) )"),
rw!("rule_40"; "(* (* ?x ?y) ?z)" => "(* ?x (* ?y ?z) )"),
rw!("rule_41"; "(* (- 0 ?x) ?y)" => "(- 0 (* ?x ?y) )"),
rw!("rule_42"; "(- ?x (+ ?y ?x) )" => "(- 0 ?y)"),
rw!("rule_44"; "(- 0 (+ ?x 1) )" => "(- -1 ?x)"),
rw!("rule_45"; "(- 0 (+ 1 ?x) )" => "(- -1 ?x)"),
rw!("rule_46"; "(- 0 (- ?x 1) )" => "(- 1 ?x)"),
rw!("rule_47"; "(- (+ ?x ?y) ?y)" => "?x"),
rw!("rule_49"; "(- (- ?x ?y) ?z)" => "(- ?x (+ ?y ?z) )"),
rw!("rule_51"; "(+ (* ?x ?y) (* ?x ?z) )" => "(* ?x (+ ?y ?z) )"),
rw!("rule_52"; "(+ (* ?x ?y) (* ?z ?x) )" => "(* ?x (+ ?y ?z) )"),
rw!("rule_53"; "(+ (* ?x ?y) (* ?y ?z) )" => "(* ?y (+ ?x ?z) )"),
rw!("rule_54"; "(* ?x (* ?x (pow ?y 2) ) )" => "(pow (* ?x ?y) 2)"),
rw!("rule_55"; "(pow ?x 0)" => "1" if is_not_zero("?x")),
rw!("rule_56"; "(/ ?x ?x)" => "1" if is_not_zero("?x")),
rw!("rule_57"; "(* ?x (/ 1 ?x) )" => "1" if is_not_zero("?x")),
rw!("rule_58"; "(pow ?x -1 )" => "(/ 1 ?x)" if is_not_zero("?x")),
rw!("rule_59"; "(* ?y (pow ?x -1 ) )" => "(/ ?y ?x)" if is_not_zero("?x")),
rw!("rule_60"; "(* (pow ?x ?y) (pow ?x ?z) )" => "(pow ?x (+ ?y ?z) )" if is_not_zero("?x")),
rw!("assoc_add"; "(+ ?x (+ ?y ?z) )" => "(+ (+ ?x ?y) ?z)"),
rw!("assoc_mul"; "(* ?x (* ?y ?z) )" => "(* (* ?x ?y) ?z)"),
rw!("sub_canon"; "(- ?x ?y)" => "(+ ?x (* -1 ?y) )"),
rw!("div_canon"; "(/ ?x ?y)" => "(* ?x (pow ?y -1 ) )" if is_not_zero("?y")),
rw!("add_zero"; "?x" => "(+ ?x 0)"),
rw!("mul_one"; "?x" => "(* ?x 1)"),
rw!("distribute"; "(* ?x (+ ?y ?z) )" => "(+ (* ?x ?y) (* ?x ?z) )"),
rw!("pow2"; "(pow ?x 2)" => "(* ?x ?x)"),
]),

]}
