[package]
name = "kbc-test"
version = "0.1.0"
edition = "2024"

[dependencies]
egg = "0.10.0"
itertools = "0.14.0"
ordered-float = "3.0.0"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.143"
